# Generated by Django 4.0.3 on 2022-04-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('party_size', models.CharField(max_length=20)),
                ('dining_time', models.CharField(max_length=20)),
                ('seated', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
            ],
        ),
    ]
