# Generated by Django 4.0.3 on 2022-04-29 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('guest', models.CharField(default='Empty', max_length=20)),
                ('seats', models.IntegerField()),
                ('time_seated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wait',
            name='dining_time',
        ),
        migrations.RemoveField(
            model_name='wait',
            name='left',
        ),
        migrations.RemoveField(
            model_name='wait',
            name='seated',
        ),
        migrations.AddField(
            model_name='wait',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
