# Generated by Django 4.0.3 on 2022-04-29 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_table_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time_seated',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 2, 37, 11, 552184)),
        ),
        migrations.AlterField(
            model_name='wait',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 2, 37, 11, 551906)),
        ),
    ]
