# Generated by Django 4.0.3 on 2022-04-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0006_alter_table_time_seated_alter_wait_arrival_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='guest',
            new_name='party',
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='wait',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
