# Generated by Django 4.0.3 on 2022-04-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0007_rename_guest_table_party_alter_table_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wait',
            name='assign_sugg',
            field=models.IntegerField(default=0),
        ),
    ]
