# Generated by Django 4.0.3 on 2022-05-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0008_wait_assign_sugg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_servers', models.IntegerField(default=0)),
                ('server_names', models.CharField(default='None', max_length=50)),
                ('tables_for_2', models.IntegerField(default=0)),
                ('tables_for_4', models.IntegerField(default=0)),
                ('tables_for_6', models.IntegerField(default=0)),
                ('tables_for_8', models.IntegerField(default=0)),
            ],
        ),
    ]
