# Generated by Django 4.0.3 on 2022-04-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('guest', models.CharField(default='Empty', max_length=20)),
                ('seats', models.IntegerField()),
                ('time_seated', models.TimeField()),
            ],
        ),
    ]
